<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DocumentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('documents')->insert([
            [
                'title' => 'Acta de Reunión Extraordinaria',
                'description' => 'Resumen de las actividades realizadas durante el año pasado.',
                'category_id' => 2,
                'status_id' => 1,
                'created_by' => 6,
                'received_date' => '2024-12-21',
                'created_at' => '2024-12-24',
                'updated_at' => '2025-01-02',
            ],
            [
                'title' => 'Oficio de Notificación',
                'description' => 'Este documento detalla los acuerdos alcanzados en la reunión.',
                'category_id' => 1,
                'status_id' => 1,
                'created_by' => 15,
                'received_date' => '2024-12-17',
                'created_at' => '2024-12-20',
                'updated_at' => '2024-12-23',
            ],
            [
                'title' => 'Informe Anual de Actividades',
                'description' => 'Se enumeran los temas discutidos en la reunión extraordinaria.',
                'category_id' => 4,
                'status_id' => 3,
                'created_by' => 16,
                'received_date' => '2024-12-19',
                'created_at' => '2024-12-22',
            ],
            [
                'title' => 'Acta Número 244',
                'description' => 'Contiene información relevante sobre el caso en cuestión.',
                'category_id' => 2,
                'status_id' => 3,
                'created_by' => 3,
                'received_date' => '2024-12-13',
                'created_at' => '2024-12-16',
                'updated_at' => '2024-12-22',
            ],
            [
                'title' => 'Acta de Reunión Extraordinaria',
                'description' => 'Registro de los puntos tratados en la asamblea general.',
                'category_id' => 2,
                'status_id' => 1,
                'created_by' => 8,
                'received_date' => '2025-01-12',
                'created_at' => '2025-01-15',
            ],
            [
                'title' => 'Expediente de Carlos Mendoza',
                'description' => 'Notificación formal enviada a las partes interesadas.',
                'category_id' => 3,
                'status_id' => 3,
                'created_by' => 12,
                'received_date' => '2024-12-24',
                'created_at' => '2024-12-27',
            ],
            [
                'title' => 'Oficio de Notificación',
                'description' => 'Detalles específicos sobre el expediente de Carlos Mendoza.',
                'category_id' => 1,
                'status_id' => 2,
                'created_by' => 18,
                'received_date' => '2024-12-15',
                'created_at' => '2024-12-18',
            ],
            [
                'title' => 'Acta Número 244',
                'description' => 'Registro de los puntos tratados en la asamblea general.',
                'category_id' => 2,
                'status_id' => 3,
                'created_by' => 4,
                'received_date' => '2025-01-09',
                'created_at' => '2025-01-12',
            ],
            [
                'title' => 'Acta de Reunión Extraordinaria',
                'description' => 'Informe detallado de las reparaciones realizadas.',
                'category_id' => 2,
                'status_id' => 2,
                'created_by' => 20,
                'received_date' => '2025-01-07',
                'created_at' => '2025-01-10',
                'updated_at' => '2025-01-17',
            ],
            [
                'title' => 'Expediente de Wilson Gulliber',
                'description' => 'Se solicita el presupuesto para la ejecución del proyecto.',
                'category_id' => 3,
                'status_id' => 1,
                'created_by' => 2,
                'received_date' => '2024-12-15',
                'created_at' => '2024-12-18',
                'updated_at' => '2024-12-23',
            ],
            [
                'title' => 'Acta de Reunión Mensual',
                'description' => 'Resumen de las actividades realizadas en la reunión mensual.',
                'category_id' => 2,
                'status_id' => 1,
                'created_by' => 1,
                'received_date' => '2024-12-20',
                'created_at' => '2024-12-22',
                'updated_at' => '2024-12-24',
            ],
            [
                'title' => 'Informe de Actividades 2024',
                'description' => 'Informe de actividades realizadas durante el 2024.',
                'category_id' => 4,
                'status_id' => 2,
                'created_by' => 2,
                'received_date' => '2024-12-18',
                'created_at' => '2024-12-20',
                'updated_at' => '2024-12-22',
            ],
            [
                'title' => 'Solicitud de Reunión Extraordinaria',
                'description' => 'Solicitud para realizar una reunión extraordinaria.',
                'category_id' => 1,
                'status_id' => 1,
                'created_by' => 3,
                'received_date' => '2024-12-21',
                'created_at' => '2024-12-23',
                'updated_at' => '2024-12-25',
            ],
            [
                'title' => 'Contrato de Servicios',
                'description' => 'Contrato formal de servicios para el proyecto.',
                'category_id' => 3,
                'status_id' => 2,
                'created_by' => 4,
                'received_date' => '2024-12-10',
                'created_at' => '2024-12-12',
                'updated_at' => '2024-12-14',
            ],
            [
                'title' => 'Plan de Acción 2025',
                'description' => 'Planificación de acciones para el año 2025.',
                'category_id' => 2,
                'status_id' => 3,
                'created_by' => 5,
                'received_date' => '2024-12-15',
                'created_at' => '2024-12-17',
                'updated_at' => '2024-12-19',
            ],
            [
                'title' => 'Evaluación de Proyectos 2024',
                'description' => 'Informe con evaluación de los proyectos realizados este año.',
                'category_id' => 4,
                'status_id' => 1,
                'created_by' => 6,
                'received_date' => '2024-12-13',
                'created_at' => '2024-12-15',
                'updated_at' => '2024-12-17',
            ],
            [
                'title' => 'Informe de Presupuesto',
                'description' => 'Informe detallado sobre el presupuesto utilizado.',
                'category_id' => 3,
                'status_id' => 2,
                'created_by' => 7,
                'received_date' => '2024-12-25',
                'created_at' => '2024-12-27',
                'updated_at' => '2024-12-29',
            ],
            [
                'title' => 'Acta de Reunión de Comité',
                'description' => 'Acta con los acuerdos alcanzados en la reunión del comité.',
                'category_id' => 2,
                'status_id' => 3,
                'created_by' => 8,
                'received_date' => '2024-12-14',
                'created_at' => '2024-12-16',
                'updated_at' => '2024-12-18',
            ],
            [
                'title' => 'Informe de Avance de Proyecto',
                'description' => 'Informe detallado del avance del proyecto en diciembre.',
                'category_id' => 1,
                'status_id' => 2,
                'created_by' => 9,
                'received_date' => '2024-12-22',
                'created_at' => '2024-12-24',
                'updated_at' => '2024-12-26',
            ],
            [
                'title' => 'Revisión de Políticas Internas',
                'description' => 'Revisión y actualización de las políticas internas de la empresa.',
                'category_id' => 3,
                'status_id' => 1,
                'created_by' => 10,
                'received_date' => '2024-12-11',
                'created_at' => '2024-12-13',
                'updated_at' => '2024-12-15',
            ],

        ]);
    }
}
